### ISSUE TITLE
Automatizar página do autor e modificação de layout

### ISSUE THREAD

**Issue by BrancaSchulz** [ForaDoEixo/redeninja#10]

**Comment by uira** [comment]
@BrancaSchulz precisa colocar aqui o print de como deve ser a página

**Comment by raissagal** [comment]
![captura de tela 2017-03-28 as 11 37 57](https://cloud.githubusercontent.com/assets/14958399/24425035/01f3810e-13d9-11e7-9b28-58f372f3931d.png)
proposta de ficar assim a página do colunista

**Comment by iwasthesword** [comment]
Commitado em 2bc56f8
