### ISSUE TITLE
Inserir plugin de coments do facebook para o post

### ISSUE THREAD

**Issue by raissagal** [ForaDoEixo/redeninja#13]
exemplo
![captura de tela 2017-03-29 as 00 55 24](https://cloud.githubusercontent.com/assets/14958399/24437928/74157f3a-141a-11e7-8fb4-b0fc63caa514.png)

https://ninja.oximity.com/article/Monique-Prada-%C3%A9-a-nova-colunista-1

**Comment by iwasthesword** [comment]
Implementado em f5fee909a68a0dd44ff0c97b2848a2b0b67f8d75
