### ISSUE TITLE
Mudar padrão de borda para legenda de fotos

### ISSUE THREAD

**Issue by raissagal** [ForaDoEixo/redeninja#14]
dá pra ser sem essa borda cinza? 
![captura de tela 2017-04-07 as 00 48 47](https://cloud.githubusercontent.com/assets/14958399/24784890/048dc73a-1b2c-11e7-8daa-08303652b404.png)

**Comment by raissagal** [comment]
Dá pra ser sem essa borda cinza?

**Comment by uira** [comment]
@iwasthesword isso aqui o @wforte88 mandou a solução por email. Tu chegou a ver?

`.et_post_meta_wrapper h1 {
font-family: Times, Arial; 
font-size: 38pt;
width: 73.625%;
}


.single article, .page article {
box-shadow: none
}

.wp-caption {
border:none; 
background:none; 
color: #666; 
line-height:normal;
}
`

**Comment by wforte88** [comment]
O código desta issue é este:

.wp-caption {
border:none; 
background:none; 
color: #666; 
line-height:normal;
}

**Comment by iwasthesword** [comment]
Preciso confirmar mas acho que essa é uma issue antiga de quando estavamos usando o Divi Builder, que adicionava um css custom pra legenda. Não deveria ocorrer mais

**Comment by uira** [comment]
@iwasthesword não. isso é o css padrão de legenda de fotos. Mas vale testar.
