### ISSUE TITLE
Testar Multiautor

### ISSUE THREAD

**Issue by wforte88** [ForaDoEixo/redeninja#16]
Testar plugin da Rede Livre com o Extra e avaliar processo de criação de usuários dos colunistas.

**Comment by iwasthesword** [comment]
Eu testei o plugin Co-Authors Plus que esta la na redelivre mas ele não cria um usuario/author em si, então não funciona com o sistema que estamos usando.

**Comment by iwasthesword** [comment]
Implementado direto no wordpress sem precisar de plugin 2bc56f8959f56405d0979acfbb157a7435a832be
