### ISSUE TITLE
o tema pai é o wp-divi-3

### ISSUE THREAD

**Issue by jacsonp** [ForaDoEixo/redeninja#18]
wp-divi vem do fornecedor do tema, o -3 vem da versão da redelivre, para descobrir a pasta, tinha que ter instalador a redelivre ou olhado aqui:
![image](https://cloud.githubusercontent.com/assets/3977652/24892710/027e4876-1e55-11e7-95d7-905157bf9eb4.png)
Tem um botão: Informações do tema

**Comment by uira** [comment]
Ah seu sapeca! Vou já commitar.
