### ISSUE TITLE
Intalar plugin de Multiautores

### ISSUE THREAD

**Issue by BrancaSchulz** [ForaDoEixo/redeninja#2]

**Comment by raissagal** [comment]
Há a possibilidade de configurar o autor que vai para o link permanente? 
Consegui ativar o plugin e incluir autor, mas no meta não aparece e nem no link permanente
![img_2017-03-29 02 17 04](https://cloud.githubusercontent.com/assets/14958399/24439636/d21a5398-1425-11e7-94fc-afc7f7a8f96d.jpg)

na imagem o que está circulado é o tema do post, mas eu já tinha configurado pra mostrar o autor
