### ISSUE TITLE
Capa

### ISSUE THREAD

**Issue by raissagal** [ForaDoEixo/redeninja#23]
o layout da página com os autores está desconfigurado
![captura de tela 2017-04-14 as 02 43 34](https://cloud.githubusercontent.com/assets/14958399/25035073/ab774f40-20c1-11e7-88e8-ae5433804733.png)

**Comment by raissagal** [comment]
Os primeiros autores não estão clicáveis

**Comment by raissagal** [comment]
Não aparece as redes sociais na capa

**Comment by raissagal** [comment]
fonte do menu muito fina 
![captura de tela 2017-04-14 as 03 26 45](https://cloud.githubusercontent.com/assets/14958399/25035163/3bc33f82-20c2-11e7-8b9f-502a25637f8e.png)

**Comment by iwasthesword** [comment]
A capa ainda não está finalizada, to terminando de codar o layout que o pira me passou.

Sobre o header, tinha batido isso com ele também, precisamos discutir mais um pouco pra fechar isso

**Comment by iwasthesword** [comment]
Implementado 40463793845a9e482f9592e05534991f8841bf0c
