### ISSUE TITLE
Página autor

### ISSUE THREAD

**Issue by raissagal** [ForaDoEixo/redeninja#24]
tá aparecendo o máximo de 5 posts por autor, o ideal é deixar 10 e depois disso começar a contar a paginação

**Comment by raissagal** [comment]
no mobile, aparece só a hora de postagem de cada post, é preciso entrar o padrão de data e hora
![img_2017-04-14 10 07 00](https://cloud.githubusercontent.com/assets/14958399/25043967/1ee7a12c-20fa-11e7-855c-bc04c842bbfc.jpg)

**Comment by iwasthesword** [comment]
Pagina do autor ainda não ta fechada também

**Comment by iwasthesword** [comment]
Implementado 75b54c54510782beb90e99d256452f648f9ca9dc
