### ISSUE TITLE
Post 

### ISSUE THREAD

**Issue by raissagal** [ForaDoEixo/redeninja#25]
no facebook ele tá compartilhando por padrão a foto do autor. ![captura de tela 2017-04-14 as 09 42 26](https://cloud.githubusercontent.com/assets/14958399/25043612/8e94d740-20f7-11e7-9817-2637813054ca.png)

o ideal é que seja a imagem destacada e o resumo do texto

**Comment by raissagal** [comment]
a coluna de texto tá muito fina, dá pra aumentar um pouco mais de cada lado

![captura de tela 2017-04-14 as 09 48 36](https://cloud.githubusercontent.com/assets/14958399/25043687/261aa9e6-20f8-11e7-9b7d-4e60dc824e6e.png)

**Comment by raissagal** [comment]
aumentar o peso uma medida a mais do conheça outros colunistas
![captura de tela 2017-04-14 as 09 48 55](https://cloud.githubusercontent.com/assets/14958399/25043705/3a514064-20f8-11e7-9f7d-8d0a2b5edf04.png)

**Comment by raissagal** [comment]
No mobilie, a separação entre data e hora está indo sem o reloginho 
tá assim
![img_2017-04-14 09 13 22](https://cloud.githubusercontent.com/assets/14958399/25043019/03cc9200-20f3-11e7-9397-f0ad48b4aff4.jpg)


era pra ficar assim
![captura de tela 2017-04-14 as 09 15 17](https://cloud.githubusercontent.com/assets/14958399/25043005/e6dcc89a-20f2-11e7-89c8-11c9d6aa0310.png)

**Comment by iwasthesword** [comment]
Implementado dd79c995a44d4e2d50364108dccfa664269774b9
