### ISSUE TITLE
Aumentar limite de colunas por autor

### ISSUE THREAD

**Issue by raissagal** [ForaDoEixo/redeninja#42]
Na página de cada autor está limitado de colunas para 20, as demais não são encontráveis no site. Precisa ou aumentar o limite ou colocar paginação para isso

**Comment by steffandsv** [comment]
Como a página dos autores está construída? Se foi modificada, favor entrar em Aparência->Editor ... canto inferior direito-> "author.php" e copiar o código para nos mostrar
