### ISSUE TITLE
Inserção de nova fonte para os títulos

### ISSUE THREAD

**Issue by BrancaSchulz** [ForaDoEixo/redeninja#7]

**Comment by BrancaSchulz** [comment]
Fonte: https://www.fonts.com/font/adobe/times-new-roman/bold-condensed

**Comment by raissagal** [comment]
aqui como ficaria com a fonte comprada 
![img_2017-03-28 17 37 24](https://cloud.githubusercontent.com/assets/14958399/24426218/49f5e484-13dd-11e7-9057-a6cc38842752.jpg)

**Comment by iwasthesword** [comment]
Commitado em ec9bf05
